import Database from "better-sqlite3";

const db = new Database("portfolio.db");

const creditsText = `ARTIST | ZICO, CRUSH

PRODUCTION | BANGJAEYEOB FILM
DIRECTOR | BANG JAE YEOB, NANY KIM (NÄN)
AD | AHN JIMIN, BAE SOYEON, BAEK SEUNGHEE, AHN YEOEUN, JEON JAEMIN
PRODUCER | PARK CHANYOUNG, BAEK SEUNGHOON (HATTRICK)

D.O.P | LEE JINHYUK
FOCUS PULLER | SHIN DONGHYEOK
2ND | JEONG GUNWOO
3RD | KIM MINSUNG
DIT | LEE SOOYEONG

GAFFER | OH JONGHWAN (HIGH LIGHT)
1ST | KIM HYUNGGYOON
2ND | PARK SEONGHUN, PARK KWANGHO, KIM TAEYANG
3RD | YEOM SEUNGHYUK, SONG SEUNGEUN, KIM SEONGJU, SON JIWON, LEE WONJUN, LEE HYEONWOO
GENERATOR | YU JINSUN

ROBOT ARM (M.C.C) OPERATOR | KIM DAEHONG (AXSIX)
ROBOT ARM ASSISTANT | CHOI SEJUN, JUNG MINKYU, CHOI HYUNJUN, OH SEUNGJUN, KIM KIDONG

KEY GRIP | HWANG JIIN
1ST | CHOI DAEHEON
2ND | OH CHIHUN, LEE WOUNGBEE

JIMMY JIB OPERATOR | JI YOONGU
JIMMY JIB ASSISTANT | YOO JINHO, YOO SEUNGJUN, YOO GWANGHYUN

PRODUCTION SUPPORT | LEE KYOUNGJIN
TEAM LEADER | LEE HEECHAN
TEAM MEMBER | KIM DABIN, SEO JUNGYU, YANG YUJIN, WOO BEAKHO, LEE DONGWON, LEE SANGMI

EDIT | BAE SOYEON, JEON JAEMIN (BANGJAEYEOB FILM)

VFX STUDIO | ORB HAUS
VFX SUPERVISOR / 3D ARTIST | ZADDICTED
VFX PRODUCER | T LEENA
2D VFX / COMPOSITION | LAMIE DOAN

2D CLEAN&BEAUTY | SHIN YEJIN (SSSS)
2D CLEAN&BEAUTY ASSISTANT | KIM MIJI

2D DESIGN | JEON JAEMIN

DI | LUCID COLOUR
COLORIST | NA SOMI
DI CREW | LEE MINKYUNG
DI SUPERVISOR | YEOM JIYUN
DI PRODUCER | KIM SUHYEON
DI MANAGER | PARK HEEJIN

SPECIAL THANKS TO | KIM NAMSEOK`;

const result = db.prepare("UPDATE projects SET credits = ? WHERE title LIKE '%ZICO X Crush%'").run(creditsText);
console.log("Updated rows:", result.changes);
